### ISSUE TITLE
Hello, can you upload the source code of elfen.so?

### ISSUE THREAD

**Issue by yuejiyueren** [nikhilh-20/ELFEN_images#3]
I want to know what work I need to do to compile the kernel myself and What's in elfen.so

**Comment by nikhilh-20** [comment]
The steps I took to compile the image is a long list. I'll write a blog about it one of these days.
Until then, I suggest you take a look at how to use [buildroot](https://buildroot.org/). That's the tooling I use.

`elfen.so` is a library that is used to trace a few string-related functions in libc. I'll upload the source code soon.
